title: Awesome Life
author: Ned
email: htsheu99@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  C#, dotnet, Vue, React, typescript, golang, mssql...

# social links
twitter_username: -- # DO NOT include the @ character, or else the build will fail!
github_username:  NedHsu # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
